# fly.toml file generated for basha on 2022-11-26T20:35:46-06:00

app = "basha"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 3000
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
interval = 10000
grace_period = "5s"
method = "get"
path = "/api/info"
protocol = "http"
restart_limit = 0
timeout = 5000
tls_skip_verify = true
[services.http_checks.headers]
