services:
  - type: web
    name: basha
    env: docker
    repo: https://github.com/ajakate/basha.git
    branch: render
    plan: free
    region: oregon
    numInstances: 1
    healthCheckPath: /api/info
    envVars:
      - key: TOKEN_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: app-db
          property: connectionString
databases:
  - name: app-db
    region: oregon
