services:
  - type: web
    name: basha
    env: docker
    repo: https://github.com/ajakate/basha.git
    branch: style
    plan: free
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: TOKEN_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false